### ISSUE TITLE
tracing? bug for full scale example in logsums branch

### ISSUE THREAD

**Issue by bstabler** [UDST/activitysim#193]
Ran into a tracing? bug when running the latest logsums branch on the full example.

```
Traceback (most recent call last):
  File "simulation.py", line 50, in <module>
    pipeline.run(models=_MODELS, resume_after=resume_after)
  File "e:\projects\asim\activitysim\activitysim\core\pipeline.py", line 496, in run
    run_model(model)
  File "e:\projects\asim\activitysim\activitysim\core\pipeline.py", line 422, in run_model
    orca.run([model_name])
  File "C:\Anaconda2\lib\site-packages\orca\orca.py", line 1876, in run 
    step()
  File "C:\Anaconda2\lib\site-packages\orca\orca.py", line 780, in __call__
    return self._func(**kwargs)
  File "e:\projects\asim\activitysim\activitysim\abm\models\school_location.py", line 116, in school_location_sample
    trace_label=trace_hh_id and 'school_location_sample.%s' % school_type)
  File "e:\projects\asim\activitysim\activitysim\core\interaction_sample.py", line 380, in interaction_sample
    tracing.extend_trace_label(trace_label, 'chunk_%s' % i))
  File "e:\projects\asim\activitysim\activitysim\core\interaction_sample.py", line 287, in _interaction_sample
    pick_group = choices_df.groupby([choosers.index.name, alt_col_name])
  File "C:\Anaconda2\lib\site-packages\pandas\core\generic.py", line 3748, in groupby
    sort=sort, group_keys=group_keys, squeeze=squeeze)
  File "C:\Anaconda2\lib\site-packages\pandas\core\groupby.py", line 1428, in groupby
    return klass(obj, by, **kwds)
  File "C:\Anaconda2\lib\site-packages\pandas\core\groupby.py", line 345, in __init__
    level=level, sort=sort)
  File "C:\Anaconda2\lib\site-packages\pandas\core\groupby.py", line 2398, in _get_grouper
    in_axis, name, gpr = True, gpr, obj[gpr]
  File "C:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 1992, in __getitem__
    return self._getitem_column(key)
  File "C:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 1999, in _getitem_column
    return self._get_item_cache(key)
  File "C:\Anaconda2\lib\site-packages\pandas\core\generic.py", line 1345, in _get_item_cache
    values = self._data.get(item)
  File "C:\Anaconda2\lib\site-packages\pandas\core\internals.py", line 3225, in get
    loc = self.items.get_loc(item)
  File "C:\Anaconda2\lib\site-packages\pandas\indexes\base.py", line 1878, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas\index.c:4027)
  File "pandas\index.pyx", line 157, in pandas.index.IndexEngine.get_loc (pandas\index.c:3891)
  File "pandas\hashtable.pyx", line 675, in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:12408)
  File "pandas\hashtable.pyx", line 683, in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:12359)
KeyError: 'PERID'
Closing remaining open files:data\skims.omx...doneoutput\pipeline.h5...donedata\mtc_asim.h5...done
```

**Comment by bstabler** [comment]
Same error with tracing turned off as well

**Comment by toliwaga** [comment]
Did you reinstall the asim env  recently?

what version of pandas are you running? I am betting it is pre 0.20.1

groupby allows grouping on named index as well as columns starting with 0.20.1, which is what I was doing.

Anyway, I changed the order of code (moved set_index after groupby) so this should now work even with older versions. 

Also added num_chunks arg to chunk iterators and chunk tracing per #176

**Comment by bstabler** [comment]
It looks like we've got pandas 0.18 on the server.  Regardless, it's now running.  Thanks.
